Copy tmc-run from image

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,3 +1,8 @@
 #!/bin/bash
 
+if [ -e /tmc-run ]; then
+  echo "Copying tmc-run from the image"
+  cp /tmc-run tmc-run || echo "Copying tmc-run failed"
+fi
+
 ( set +e; ./tmc-run; echo -n $? > exit_code.txt; true )
